"""empty message

Revision ID: 1577a07ca3e5
Revises: 761c2f5ad449
Create Date: 2025-12-18 15:28:38.271398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1577a07ca3e5'
down_revision: Union[str, Sequence[str], None] = '761c2f5ad449'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('mission_spy_cat_fkey'), 'mission', type_='foreignkey')
    op.create_foreign_key(None, 'mission', 'spy_cat', ['spy_cat'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'mission', type_='foreignkey')
    op.create_foreign_key(op.f('mission_spy_cat_fkey'), 'mission', 'spy_cat', ['spy_cat'], ['id'])
    # ### end Alembic commands ###
