"""empty message

Revision ID: 1d0ebbc55247
Revises: 488f2d217948
Create Date: 2025-12-18 12:38:16.344514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d0ebbc55247'
down_revision: Union[str, Sequence[str], None] = '488f2d217948'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('target', sa.Column('country', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('target', 'country')
    # ### end Alembic commands ###
