"""empty message

Revision ID: 5118aa8eca5c
Revises: 1d0ebbc55247
Create Date: 2025-12-18 13:05:33.773048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5118aa8eca5c'
down_revision: Union[str, Sequence[str], None] = '1d0ebbc55247'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mission', sa.Column('target', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'mission', 'target', ['target'], ['id'])
    op.add_column('spy_cat', sa.Column('name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('spy_cat', 'name')
    op.drop_constraint(None, 'mission', type_='foreignkey')
    op.drop_column('mission', 'target')
    # ### end Alembic commands ###
