"""empty message

Revision ID: 6bff562377fb
Revises: 5118aa8eca5c
Create Date: 2025-12-18 13:08:12.097826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bff562377fb'
down_revision: Union[str, Sequence[str], None] = '5118aa8eca5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'spy_cat', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'spy_cat', type_='unique')
    # ### end Alembic commands ###
