"""empty message

Revision ID: 761c2f5ad449
Revises: 6bff562377fb
Create Date: 2025-12-18 14:28:39.888406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '761c2f5ad449'
down_revision: Union[str, Sequence[str], None] = '6bff562377fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mission', 'spy_cat',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mission', 'spy_cat',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
